### ISSUE TITLE
Right restriction between users

### ISSUE THREAD

**Issue by Floyer007** [fpiesche/docker-sftp-server#18]
Is there a way to restrict the access between user-folders?

If I have multiple users each of their home directories will be created correctly.
But if I sftp into one of them and go one level back via `cd ..`, I can easily change to another home directory.

**Comment by fpiesche** [comment]
Not in the default setup but honestly for security reasons users should be chrooted to their home directory anyway. Again I'm using this in my personal setup where this isn't something I've been concerned about but I'll see about implementing an enforced chroot for users.

**Comment by Floyer007** [comment]
Same here, but it just was something I was curious to try, in case I will add more users later.

**Comment by fpiesche** [comment]
v2022.08.04, just built earlier, should make this work!

**Comment by Floyer007** [comment]
Thanks for looking into this as well.

Seems to work fine in the latest image v2022.08.04
I can't change the directory a level back to /home anymore or change directly to another users home-folder.

**Comment by fpiesche** [comment]
Thanks for verifying that! :)
